// API Response Helpers
export {
  successResponse,
  paginatedResponse,
  createdResponse,
  deletedResponse,
  errorResponse,
  handleError,
  validateRequestBody,
  extractPaginationParams,
  noContentResponse,
  redirectResponse,
  isSuccessResponse,
  throwFromResponse,
} from './api-response';

// Utility Helpers
export {
  generateId,
  formatDate,
  formatTime,
  formatDateTime,
  timeAgo,
  slugify,
  capitalize,
  enumToDisplay,
  isValidEmail,
  isValidPhone,
  maskEmail,
  maskPhone,
  isEmpty,
  deepClone,
  deepMerge,
  pick,
  omit,
  groupBy,
  parseQueryParams,
  buildQueryString,
  calculatePercentageChange,
  formatCurrency,
  formatNumber,
  truncate,
  highlightText,
  sleep,
  retry,
} from './utils';

// Auth Helpers
export {
  generateToken,
  decodeToken,
  extractTokenFromHeader,
  hasRole,
  hasPermission,
  verifyPermission,
  hashPassword,
  comparePassword,
  generateResetToken,
  createSessionData,
  isValidEmail as authIsValidEmail,
  validatePasswordStrength,
  generateSessionId,
  verifyIpAddress,
  isAccountActive,
  isAccountSuspended,
  getUserInitials,
  sanitizeUserData,
} from './auth';

// Logger Helpers
export {
  LogLevel,
  type ILogger,
  ConsoleLogger,
  setLogger,
  getLogger,
  createLogger,
  logRequest,
  logResponse,
  logDatabaseOperation,
  logErrorWithContext,
  logPerformance,
  PerformanceMarker,
  mark,
} from './logger';

// Error Handler Helpers
export {
  mapErrorToResponse,
  assert,
  assertExists,
  assertAuthorized,
  assertHasPermission,
  tryCatch,
  validateRequiredFields,
  handleDatabaseError,
  withFallback,
  retryWithBackoff,
  withTimeout,
  sanitizeErrorMessage,
  getErrorDetails,
} from './error-handler';
