import { BaseService } from '@/lib/services/base.service';
import { IReport, ReportType, ReportStatus } from '@/lib/types';
import { reports as mockReports } from '@/lib/admin-data';

/**
 * Reports Service - handles report generation and management
 */
export class ReportsService extends BaseService<IReport> {
  constructor() {
    super('Report', mockReports);
  }

  /**
   * Get reports by type
   */
  async getByType(type: ReportType): Promise<IReport[]> {
    return this.data.filter(r => r.type === type);
  }

  /**
   * Get reports by status
   */
  async getByStatus(status: ReportStatus): Promise<IReport[]> {
    return this.data.filter(r => r.status === status);
  }

  /**
   * Get reports generated by user
   */
  async getByUser(userId: string): Promise<IReport[]> {
    return this.data.filter(r => r.generatedBy === userId);
  }

  /**
   * Generate new report
   */
  async generateReport(data: {
    name: string;
    type: ReportType;
    dateRange: { start: string; end: string };
    generatedBy: string;
  }): Promise<IReport> {
    const newReport: IReport = {
      id: this.generateId(),
      ...data,
      status: ReportStatus.PENDING,
      metrics: {
        totalValue: 0,
        change: 0,
        changePercent: 0,
      },
      dataPoints: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.data.push(newReport);

    // Simulate report generation
    setTimeout(() => {
      this.finalizeReport(newReport.id);
    }, 2000);

    return newReport;
  }

  /**
   * Mark report as ready
   */
  async finalizeReport(reportId: string): Promise<IReport> {
    const report = this.data.find(r => r.id === reportId);
    if (!report) throw new Error('Report not found');

    // Generate mock data
    const totalValue = Math.floor(Math.random() * 1000000);
    const change = Math.floor(Math.random() * 500000);

    return this.update(reportId, {
      status: ReportStatus.READY,
      metrics: {
        totalValue,
        change,
        changePercent: Math.round((change / totalValue) * 100 * 100) / 100,
      },
      dataPoints: [
        { label: 'Week 1', value: Math.floor(totalValue * 0.15) },
        { label: 'Week 2', value: Math.floor(totalValue * 0.2) },
        { label: 'Week 3', value: Math.floor(totalValue * 0.25) },
        { label: 'Week 4', value: Math.floor(totalValue * 0.4) },
      ],
      updatedAt: new Date().toISOString(),
    });
  }

  /**
   * Get reports within date range
   */
  async getByDateRange(startDate: string, endDate: string): Promise<IReport[]> {
    return this.data.filter(r => {
      const rStart = new Date(r.dateRange.start);
      const rEnd = new Date(r.dateRange.end);
      const start = new Date(startDate);
      const end = new Date(endDate);
      return rStart >= start && rEnd <= end;
    });
  }

  /**
   * Search reports
   */
  async searchReports(query: string): Promise<IReport[]> {
    const lowerQuery = query.toLowerCase();
    return this.data.filter(r =>
      r.name.toLowerCase().includes(lowerQuery) ||
      r.type.toLowerCase().includes(lowerQuery)
    );
  }

  /**
   * Get report statistics
   */
  async getReportStats(): Promise<{
    total: number;
    byType: Record<ReportType, number>;
    byStatus: Record<ReportStatus, number>;
    avgMetrics: { totalValue: number; changePercent: number };
  }> {
    const types = ['sales', 'users', 'products', 'rentals', 'communities', 'revenue'] as ReportType[];
    const statuses = ['pending', 'ready', 'failed'] as ReportStatus[];

    const byType = types.reduce((acc, type) => {
      acc[type] = this.data.filter(r => r.type === type).length;
      return acc;
    }, {} as Record<ReportType, number>);

    const byStatus = statuses.reduce((acc, status) => {
      acc[status] = this.data.filter(r => r.status === status).length;
      return acc;
    }, {} as Record<ReportStatus, number>);

    const readyReports = this.data.filter(r => r.status === ReportStatus.READY);
    const avgTotalValue = readyReports.length > 0
      ? readyReports.reduce((sum, r) => sum + r.metrics.totalValue, 0) / readyReports.length
      : 0;
    const avgChangePercent = readyReports.length > 0
      ? readyReports.reduce((sum, r) => sum + r.metrics.changePercent, 0) / readyReports.length
      : 0;

    return {
      total: this.data.length,
      byType,
      byStatus,
      avgMetrics: {
        totalValue: Math.round(avgTotalValue),
        changePercent: Math.round(avgChangePercent * 100) / 100,
      },
    };
  }

  /**
   * Compare reports for trend analysis
   */
  async compareReports(reportId1: string, reportId2: string): Promise<{
    report1: IReport;
    report2: IReport;
    comparison: {
      valueDifference: number;
      percentageDifference: number;
      trend: 'up' | 'down' | 'stable';
    };
  }> {
    const report1 = await this.getById(reportId1);
    const report2 = await this.getById(reportId2);

    const valueDifference = report2.metrics.totalValue - report1.metrics.totalValue;
    const percentageDifference = valueDifference > 0
      ? (valueDifference / report1.metrics.totalValue) * 100
      : 0;

    return {
      report1,
      report2,
      comparison: {
        valueDifference,
        percentageDifference: Math.round(percentageDifference * 100) / 100,
        trend: valueDifference > 0 ? 'up' : valueDifference < 0 ? 'down' : 'stable',
      },
    };
  }

  /**
   * Export report (mock)
   */
  async exportReport(
    reportId: string,
    format: 'pdf' | 'csv' | 'excel'
  ): Promise<{ filename: string; data: string }> {
    const report = await this.getById(reportId);

    const filename = `${report.name.replace(/\s+/g, '_')}_${Date.now()}.${format}`;
    const data = JSON.stringify(report, null, 2);

    return { filename, data };
  }

  /**
   * Schedule periodic report generation
   */
  async scheduleReport(config: {
    name: string;
    type: ReportType;
    frequency: 'daily' | 'weekly' | 'monthly';
    userId: string;
  }): Promise<{ scheduleId: string; nextRunAt: string }> {
    const now = new Date();
    let nextRunAt = new Date(now);

    if (config.frequency === 'daily') {
      nextRunAt.setDate(nextRunAt.getDate() + 1);
    } else if (config.frequency === 'weekly') {
      nextRunAt.setDate(nextRunAt.getDate() + 7);
    } else if (config.frequency === 'monthly') {
      nextRunAt.setMonth(nextRunAt.getMonth() + 1);
    }

    return {
      scheduleId: this.generateId(),
      nextRunAt: nextRunAt.toISOString(),
    };
  }
}

/**
 * Export singleton instance
 */
export const reportsService = new ReportsService();
